### ISSUE TITLE
Resize and drag circle is not working in IE11 browser

### ISSUE THREAD

**Issue by Vinoth-44** [smithmicro/mapbox-gl-circle#71]
I tried the resize and drag functionality of circle but these is not working as expected. Is there any possible to give support on IE11 browser ?

**Comment by mblomdahl** [comment]
@Vinoth-44 Could you please provide steps to reproduce? And clarify what you mean by "not working as expected". Is drag/resize "not working at all" or "sort-of-working-in-an-unexpected-manner" if you try to edit the circles on https://smithmicro.github.io/mapbox-gl-circle/ ?

**Comment by ghost** [comment]
Closing this as there's no hints as to how it could be reproduced.
