### ISSUE TITLE
Very slow when using Internet Expolorer

### ISSUE THREAD

**Issue by JAugustusSmith** [smithmicro/mapbox-gl-circle#75]
I don't like using IE either, but I need to support it.
Using the demo in IE (https://smithmicro.github.io/mapbox-gl-circle/) is very slow

**Comment by mblomdahl** [comment]
@JAugustusSmith With all the complex stuff Mapbox GL is doing, I don't think it ever will be "fast" on IE! :) In my assessment, it's currently as fast as technically possible (without sacrificing performance on high-end browsers like WebKit).
