### ISSUE TITLE
react build issue

### ISSUE THREAD

**Issue by gregdymek** [smithmicro/mapbox-gl-circle#81]
hey guys,
we are using your library in 1 project,
however we faced an issue when trying to deploy to production,
in create-react-app project we are not able to build it,
it's saying it's app.js line 43, but I cannot figure out what's wrong there,
would be great if you can fix it,
thanks,
Greg

**Comment by mblomdahl** [comment]
Hi @gregdymek! Happy to hear you're using our library. But the issue presented here is not actionable, please present exact steps to reproduce and me, @akebrissman, @vtepliuk or someone might maybe possibly have a look at it when we have time to spare.
